Prueba Carrito de Compras/Models/ClienteModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Prueba_Tecnica_Carrito_de_Compra.Models
{
    public class ClienteModel
    {
        [Key]
        public string? IdCliente { get; set; }
        public string? Nombre { get; set; }
        public string? Telefono { get; set; }
        public string? Direccion { get; set; }
        public string? Correo { get; set; }
        public string? Password { get; set; }


        public List<PedidoModel>? PedidiosCliente { get; set; }


    }
}

Prueba Carrito de Compras/Models/ErrorViewModel.cs
namespace Prueba_Carrito_de_Compras.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Prueba Carrito de Compras/Models/PedidoModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Prueba_Tecnica_Carrito_de_Compra.Models
{
    public class PedidoModel
    {
        [Key]
        public int IdPedido { get; set; }
        public double TotalPago { get; set; }

        public string? IdClientePedido { get; set; }
        public ClienteModel? ClientePedido { get; set; }
        public List<ProductoPedidoModel>? ProductosPedido { get; set; }


        public void CalcularTotalPago()
        {
            if (ProductosPedido != null)
            {
                foreach (var producto in ProductosPedido)
                {
                    this.TotalPago += (producto.UnidadesCompradas * producto.PrecioCompra);
                }
            }
        }
    }
}

Prueba Carrito de Compras/Models/ProductoDisponibleModel.cs
using System.Collections.Generic;

namespace Prueba_Tecnica_Carrito_de_Compra.Models
{
    public class ProductoDisponibleModel : ProductoModel
    {
        public string? Imagen { get; set; }
        public int UnidadesDisponibles { get; set; }
        public double PrecioCompra { get; set; }
        public double PrecioVenta { get; set; }
        public bool Descuento { get; set; }
    }
}

Prueba Carrito de Compras/Models/ProductoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Prueba_Tecnica_Carrito_de_Compra.Models
{
    public class ProductoModel
    {
        [Key]
        public string? CodigoProducto { get; set; }
        public string? Nombre { get; set; }
    }
}

Prueba Carrito de Compras/Models/ProductoPedidoModel.cs
using System.Collections.Generic;

namespace Prueba_Tecnica_Carrito_de_Compra.Models
{
    public class ProductoPedidoModel : ProductoModel
    {
        public int UnidadesCompradas { get; set; }
        public double PrecioCompra { get; set; }

        public int IdPedidoProducto { get; set; }
        public PedidoModel? PedidoProducto { get; set; }
    }
}

Prueba Carrito de Compras/Controllers/ClienteModelsController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba_Tecnica_Carrito_de_Compra.Datos;
using Prueba_Tecnica_Carrito_de_Compra.Models;

namespace Prueba_Carrito_de_Compras.Controllers
{
    public class ClienteModelsController : Controller
    {
        private readonly AppDbContext _context;

        public ClienteModelsController(AppDbContext context)
        {
            _context = context;
        }
      
        public IActionResult Index()    
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult ConsultUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ClienteModel clienteModel)
        {       
            _context.Add(clienteModel);
            _context.SaveChanges();
            return RedirectToAction();  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConsultUser(ClienteModel clogin)
        {
            var user = _context.Clientes.Where(c => c.Correo.Equals(clogin.Correo)
            && c.Password.Equals(clogin.Password)).FirstOrDefault();
            return View(user);
        }

        


    }
}

Prueba Carrito de Compras/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba_Carrito_de_Compras.Models;
using System.Diagnostics;

namespace Prueba_Carrito_de_Compras.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Prueba Carrito de Compras/Controllers/ProductoDisponibleController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba_Tecnica_Carrito_de_Compra.Datos;
using Prueba_Tecnica_Carrito_de_Compra.Models;
using System.Net;


namespace Prueba_Carrito_de_Compras.Controllers
{
    public class ProductoDisponibleController : Controller
    {
        private readonly AppDbContext _context;

        public ProductoDisponibleController (AppDbContext context)
        {
            _context = context;
        }


        public IActionResult Index()
        {
            IEnumerable<ProductoDisponibleModel> consult = _context.ProductosDisponibles;
            return View(consult);
        }

        public IActionResult Details (String id)
        {
            ProductoDisponibleModel consult = _context.ProductosDisponibles.Where(p => p.CodigoProducto == id).FirstOrDefault();
            return View(consult);
        }

        public IActionResult Download(String url, String id)
        {
            String dir = "D:\\Descargas\\Producto.jpg";
            WebClient client = new WebClient();
            client.DownloadFile(url, dir);
            client.Dispose();
            ProductoDisponibleModel consult = _context.ProductosDisponibles.Where(p => p.CodigoProducto == id).FirstOrDefault();
            return View(consult);
        }

        




    }
}

Prueba Carrito de Compras/Views/ClienteModels/ConsultUser.cshtml
@model Prueba_Tecnica_Carrito_de_Compra.Models.ClienteModel

@{
  ViewData["Title"] = "ConsultUser";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model != null)
{
  <div class="text-center">
    <p>Cargar productos disponibles <a asp-controller="ProductoDisponible" asp-action="Index">Productos</a></p>
  </div>  
}    
else
{
  <div class="alert alert-primary d-flex align-items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
    class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
      <path
      d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </svg>
    <div>
      Acceso Denegado!!
    </div>
  </div>
}

Prueba Carrito de Compras/Views/ClienteModels/Create.cshtml
@model Prueba_Tecnica_Carrito_de_Compra.Models.ClienteModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body class="container">
    <div class="row justify-content-center">
        <div class="col-6 text-center">
            <h1>Informacion</h1>
        </div>    
    </div>
    <div class="row justify-content-center">
        <div class="col-4">
            <form method = "post" asp-action = "Create">
                 <div class="mb-3">
                    <label asp-for="IdCliente" class="form-label">Numero Identificacion</label>
                    <input asp-for="IdCliente" type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span asp-validation-for="IdCliente" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Nombre" class="form-label">Nombre</label>
                    <input asp-for="Nombre" type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Telefono" class="form-label">Telefono</label>
                    <input asp-for="Telefono" type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Direccion" class="form-label">Direccion</label>
                    <input asp-for="Direccion" type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Correo" class="form-label">Correo</label>
                    <input asp-for="Correo" type="email" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Password" class="form-label">Password</label>
                    <input asp-for="Password" type="password" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
               
           
                <div class="row">
                    <div class="col d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>

Prueba Carrito de Compras/Views/ClienteModels/Index.cshtml
@model Prueba_Tecnica_Carrito_de_Compra.Models.ClienteModel

@{
  ViewData["Title"] = "Index";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<body class="container">
  <div class="row justify-content-center">
    <div class="col-5">
      <div class = "container">
        <div class = "text-center">
          <a class = "align-content-center">
            <img src="https://www.clinicasdechile.cl/wp-content/uploads/2018/01/amazon_logo_rgb.jpg" alt="" width="120" height="60">
          </a>
          <h2>Iniciar sesión</h2>
        </div>   
      </div>
      <form method = "post" asp-action = "ConsultUser">
        <div class="mb-3">
          <label asp-for="Correo" class="form-label">Correo</label>
          <input asp-for="Correo" type="email" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
          <span asp-validation-for="Correo" class="text-danger"></span>
        </div>

        <div class="mb-3">
          <label asp-for="Password" class="form-label">Password</label>
          <input asp-for="Password" type="password" class="form-control" id="exampleInputName"
            aria-describedby="nameHelp">
          <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <!-- 2 column grid layout for inline styling -->
        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
            <!-- Checkbox -->
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
              <label class="form-check-label" for="form2Example31"> Remember me </label>
            </div>
          </div>

          <div class="col">
            <!-- Simple link -->
            <a href="#!">Forgot password?</a>
          </div>
        </div>

        <!-- Submit button -->
        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
          </div>
        </div>

        <!-- Register buttons -->
        <div class="text-center">
          <p>Not a member? <a asp-controller="ClienteModels" asp-action="Create">Register</a></p>
        </div>
      </form>
    </div>
  </div>
</body>

Prueba Carrito de Compras/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://m.media-amazon.com/images/I/61OnkUKFRXL._SX3000_.jpg" class="d-block w-100" alt="1 img">
        </div>
        <div class="carousel-item">
            <img src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/BankPromotions/Scotiabank/CO/2022/May/3000x1200_spa._CB621594992_.jpg"
                class="d-block w-100" alt="2 img">
        </div>
        <div class="carousel-item">
            <img src="https://images-na.ssl-images-amazon.com/images/G/01/pxd/marketing/project-rio/Rio_Gateway_Hero_Desktop_3000x1200_2X-Shop_ES._CB670798599_.jpg"
                class="d-block w-100" alt="3 img">
        </div>
        <div class="carousel-item">
            <img src="https://m.media-amazon.com/images/I/61uIjme4x8L._SX3000_.jpg"
                class="d-block w-100" alt="4 img">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Projects/JumpIn/379x304._SY304_CB449506705_.jpg" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">Envío GRATIS a Colombia</h5>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_PC_1x._SY304_CB431800965_.jpg" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">Computadoras y Accesorios</h5>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Events/2022/FathersDay/Fuji_FathersDay22_Dash_1X._SY304_CB636880260_.jpg" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">Computadoras y Accesorios</h5>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/September/Fuji_Dash_en_US._SY304_CB641328052_.jpg" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">Hogar y Cocina</h5>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Laptops_379x304_1X_en_US._SY304_CB418608471_.jpg" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">Comprar computadoras portátiles y tablets</h5>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <img class="card-img-top" src="https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2020/May/Dashboard/Fuji_Dash_Electronics_1x._SY304_CB432774322_.jpg" alt="..." />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">Electrónicos</h5>  
                        </div>
                    </div>
                </div>
            </div>
           
      
        </div>
    </div>
</section>

Prueba Carrito de Compras/Views/ProductoDisponible/Details.cshtml
@model Prueba_Tecnica_Carrito_de_Compra.Models.ProductoDisponibleModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder fs-3">@Model.Nombre</h1>
            <p class="lead fs-5 text-white-50 mb-0">Detalle del Producto</p>
        </div>
    </div>
</header>

<body>
    <div class="container">
        <div class="row p-5">
            <div class="col mb-5">
                <div class="card h-50">
                    <div>
                        <img class="card-img-top" src="@Model.Imagen" alt="..." />
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card-body p-4">
                    <div class="text-center">
                         <h2 class="fw-bolder">Detalles</h2>
                    </div>
                    <div class="text-center text-capitalize fs-5">
                        <h3>Codigo del Producto: @Model.CodigoProducto</h3>                       
                        <h3>Unidades Disponibles: @Model.UnidadesDisponibles</h3>
                        @if(@Model.Descuento){
                            <h3><span class="text-muted text-decoration-line-through"> $ @Model.PrecioVenta</span> - $ @Model.PrecioCompra</h3>                            
                        }
                        else
                        {
                            <h3>$ @Model.PrecioVenta</h3>
                        }
                            
                    </div>
                    <br />
                    <div class="text-center">
                        <button button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Comprar
                            <i class="bi bi-cart3"></i>
                        </button>
                    </div>
                    <div class="text-center">
                        <div class="text-center">
                            @Html.ActionLink("Download", "Download", new {url = @Model.Imagen, id = @Model.CodigoProducto});                              
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h5 class="modal-title" id="exampleModalLabel">@Model.Nombre</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <div class="col mb-5">
        <div class="card h-100">
            <img class="card-img-top" src="@Model.Imagen" alt="..." />
            <div class="card-body p-4">
                <div class="text-center">
                    <h5 class="fw-bolder"></h5>
                        @if(@Model.Descuento){
                            <h3><span class="text-muted text-decoration-line-through">Valor $ @Model.PrecioVenta</span> - $ @Model.PrecioCompra</h3>                            
                        }
                        else
                        {
                            <h3>Valor $ @Model.PrecioVenta</h3>
                        }
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Numero Identificacion</label>
                    <input type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp">
                    <span class="text-danger"></span>
                </div>
        </div>
      </div>
      <div class="modal-footer align-content-center">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn bg-white">
            @Html.ActionLink("Comprar", "Comprar", new {p = @Model});                                       
        </button>
      </div>
    </div>
  </div>
</div>

Prueba Carrito de Compras/Views/ProductoDisponible/Download.cshtml
@model Prueba_Tecnica_Carrito_de_Compra.Models.ProductoDisponibleModel

@{
    ViewData["Title"] = "Download";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="alert alert-primary d-flex align-items-center" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
    class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
      <path
      d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
    </svg>
    <div>
        Imagen Producto descagada en la Direccion: D:\\Descargas\\Producto.jpg @Html.ActionLink("Atras", "Details", new {id = @Model.CodigoProducto});        
    </div>
</div>

Prueba Carrito de Compras/Views/ProductoDisponible/Index.cshtml
@model IEnumerable<Prueba_Tecnica_Carrito_de_Compra.Models.ProductoDisponibleModel>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (Model.Count() > 0)
{
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Tienda de Productos</h1>
                <p class="lead fw-normal text-white-50 mb-0">Herramientas y mas...</p>
            </div>
        </div>
    </header>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                @foreach (var item in Model)
                {

                    <div class="col mb-5">
                        <div class="card h-100">
                            <img class="card-img-top" src="@item.Imagen" alt="..." />
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">@item.Nombre</h5>
                                    Precio $ @item.PrecioVenta
                                </div>
                            </div>

                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    @Html.ActionLink("Datails", "Details", new {id = @item.CodigoProducto});
                                </div>
                            </div>
                        </div>
                    </div>

                }
            </div>
        </div>
    </section>
}
else
{

}

Prueba Carrito de Compras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba_Carrito_de_Compras</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prueba_Carrito_de_Compras.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://www.clinicasdechile.cl/wp-content/uploads/2018/01/amazon_logo_rgb.jpg" alt="" width="110" height="40">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item">
                            
                        </li>
                    </ul>
                    <form class="d-flex">
                        <button class="btn btn-outline-dark" type="submit" asp-area="" asp-controller="ClienteModels" asp-action="Index">
                            Login in
                            <i class="bi bi-box-arrow-in-right"></i>
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="p-3">
            @RenderBody()
        </main>
    </div>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>